animal = "Cat"
prompts = [
    f"{animal} walking on grass, slow movements, realistic style",
    f"{animal} gently walking, grass swaying, peaceful atmosphere",
    f"{animal} strolling calmly, soft wind, realistic grass",
    f"{animal} steps lightly on soft grass, small movements",
    f"{animal} walking slowly, slight breeze moving grass",
    f"{animal} walking through calm grass, subtle movement",
    f"{animal} slow, steady pace across soft grass, natural look",
    f"{animal} walking, grass barely shifting, realistic motion",
    f"{animal} light steps on grass, slow pace, real style",
    f"{animal} walking faster, larger strides, grass swaying",
    f"{animal} running through tall grass, big movements",
    f"{animal} moving swiftly, grass bending with its steps",
    f"{animal} galloping through grass, larger motion, realistic look",
    f"{animal} energetic run, grass reacting to swift steps",
    f"{animal} fast movement, wide strides, grass swaying heavily",
    f"{animal} sprinting across the field, tall grass bending",
    f"{animal} leaps across grass, fast and fluid, realistic style",
    f"{animal} running wildly through dense grass, full motion",
    f"{animal} fast run, grass parts with each step",
    f"{animal} jumping through the grass, big motion",
    f"{animal} leaping energetically, realistic style, grass reacting",
    f"{animal} playful run, big jumps, realistic grass interaction",
    f"{animal} sprinting across a field, large strides, realistic",
    f"{animal} bounding through grass, large, natural movements",
    f"{animal} running with quick, dynamic motion, grass sways",
    f"{animal} jumping and running, quick movements, natural feel",
    f"{animal} fast-paced run through the grass, large motions",
    f"{animal} running across the field, dynamic grass movement",
    f"{animal} quick and dramatic movement, grass moving intensely"
]